#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        ddl-auto: update
#        order_inserts: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          batch_size: 50
#          lob:
#            non_contextual_creation: true
#        temp:
#          use_jdbc_metadata_defaults: false



# Datasource configuration in heroku environment
# ?ssl=true&sslmode=verify-ca&sslfactory=org.postgresql.ssl.NonValidatingFactory

server:
  context-path: /regactapi
  port: 8080


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-54-175-117-212.compute-1.amazonaws.com:5432/dfgbq42vh9l778
    driver-class-name: org.postgresql.Driver
    username: ucafnaqivtlcez
    password: 77d6d01b12fb7d56e5c712ffe65816ef3baa0336d0bff2bdb830bca5884fcc54


logging:
  level:
    root: INFO
#  file: Conficiet.log
